---
title: "Module 0"
from: markdown+emoji
page-layout: full
description: |
  R and RStudio Installation Guide
author: Jacob Jameson
---

## R and RStudio Installation Guide

<p style="color:blue;">Mac Users</p>

To Install R:

- Open an internet browser and go to [www.r-project.org](https://www.r-project.org)
- Click the "download R" link in the middle of the page under "Getting Started."
- Select a CRAN location (a mirror site) and click the corresponding link.
- Click on the "Download R for (Mac) OS X" link at the top of the page.
- Click on the file containing the latest version of R under "Files."
- Save the .pkg file, double-click it to open, and follow the installation instructions.
- Now that R is installed, you need to download and install RStudio.

To Install RStudio:

- Go to [https://www.rstudio.com]("https://www.r-project.org) and click on the "Download" button on the top right ( right above "Pricing").
- Click on "Download RStudio Desktop."
- Click on the version recommended for your system, or the latest Mac version, save the .dmg file on your computer, double-click it to open, and then drag and drop it to your applications folder.

<p style="color:blue;">Windows Users</p>
To Install R:

- Open an internet browser and go to [www.r-project.org](https://www.r-project.org).
- Click the "download R" link in the middle of the page under "Getting Started."
- Select a CRAN location (a mirror site) and click the corresponding link.
- Click on the "Download R for Windows" link at the top of the page.
- Click on the "install R for the first time" link at the top of the page.
- Click "Download R for Windows" and save the executable file somewhere on your computer.  Run the .exe file and follow the installation instructions.
- Now that R is installed, you need to download and install RStudio.


To Install RStudio:

- Go to [https://www.rstudio.com](https://www.r-project.org) and click on the "Download" button on the top right ( right above "Pricing").
- Click on "Download RStudio Desktop."
- Click on the version recommended for your system, or the latest Windows version, and save the executable file.  Run the .exe file and follow the installation instructions.    


