<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Jacob Jameson">
<meta name="dcterms.date" content="2023-09-01">
<meta name="description" content="Marginal Effects >>> Odds Ratios">
<title>Jacob Jameson - The ‘Odd’ Obsession with Odds Ratios: Making a Case for Marginal Effects in Health Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script src="../../site_libs/kePrint/kePrint.js"></script><link href="../../site_libs/lightable/lightable.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="../../my-liera.scss.css">
<meta name="twitter:title" content="Jacob Jameson - The ‘Odd’ Obsession with Odds Ratios: Making a Case for Marginal Effects in Health Research">
<meta name="twitter:description" content="Marginal Effects >>> Odds Ratios">
<meta name="twitter:image" content="https://www.jacobjameson.github.io/docs/images/profile.png">
<meta name="twitter:creator" content="@JacobCJameson">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="452">
<meta name="twitter:image-width" content="455">
</head>
<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Jacob Jameson</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="../../teaching.html">Teaching</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../dataviz.html">Data Visualization</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research.html">Research</a>
  </li>  
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link" href="../../blog.html">Blog</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jacobjameson/jacobjameson.github.io"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/JacobCJameson/"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
</ul>
<div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><nav id="TOC" role="doc-toc"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#the-math-behind-odds-ratios" id="toc-the-math-behind-odds-ratios" class="nav-link active" data-scroll-target="#the-math-behind-odds-ratios">The math behind odds ratios</a></li>
  <li><a href="#when-odds-ratios-mislead" id="toc-when-odds-ratios-mislead" class="nav-link" data-scroll-target="#when-odds-ratios-mislead">When Odds Ratios Mislead</a></li>
  <li><a href="#marginal-effects-clarity-over-confusion" id="toc-marginal-effects-clarity-over-confusion" class="nav-link" data-scroll-target="#marginal-effects-clarity-over-confusion">Marginal Effects: Clarity over Confusion</a></li>
  <li><a href="#predicted-probabilities-concrete-scenarios-over-abstract-odds" id="toc-predicted-probabilities-concrete-scenarios-over-abstract-odds" class="nav-link" data-scroll-target="#predicted-probabilities-concrete-scenarios-over-abstract-odds">Predicted Probabilities: Concrete Scenarios Over Abstract Odds</a></li>
  <li>
<a href="#demonstrating-with-real-world-data" id="toc-demonstrating-with-real-world-data" class="nav-link" data-scroll-target="#demonstrating-with-real-world-data">Demonstrating with “Real-World” Data</a>
  <ul class="collapse">
<li><a href="#modeling-and-results" id="toc-modeling-and-results" class="nav-link" data-scroll-target="#modeling-and-results">Modeling and Results</a></li>
  <li><a href="#marginal-effects-and-interpretation" id="toc-marginal-effects-and-interpretation" class="nav-link" data-scroll-target="#marginal-effects-and-interpretation">Marginal Effects and Interpretation</a></li>
  </ul>
</li>
  <li>
<a href="#average-marginal-effects-a-comprehensive-view" id="toc-average-marginal-effects-a-comprehensive-view" class="nav-link" data-scroll-target="#average-marginal-effects-a-comprehensive-view">Average Marginal Effects: A Comprehensive View</a>
  <ul class="collapse">
<li><a href="#computing-the-average-marginal-effects" id="toc-computing-the-average-marginal-effects" class="nav-link" data-scroll-target="#computing-the-average-marginal-effects">Computing the Average Marginal Effects</a></li>
  <li><a href="#interpreting-the-ames" id="toc-interpreting-the-ames" class="nav-link" data-scroll-target="#interpreting-the-ames">Interpreting the AMEs</a></li>
  </ul>
</li>
  <li><a href="#visualizing-predicted-probabilities" id="toc-visualizing-predicted-probabilities" class="nav-link" data-scroll-target="#visualizing-predicted-probabilities">Visualizing Predicted Probabilities</a></li>
  <li><a href="#conclusion-a-call-to-transition" id="toc-conclusion-a-call-to-transition" class="nav-link" data-scroll-target="#conclusion-a-call-to-transition">Conclusion: A Call to Transition</a></li>
  </ul></nav>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">The ‘Odd’ Obsession with Odds Ratios: Making a Case for Marginal Effects in Health Research</h1>
  <div class="quarto-categories">
    <div class="quarto-category">marginal effects</div>
  </div>
  </div>

<div>
  <div class="description">
    Marginal Effects &gt;&gt;&gt; Odds Ratios
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jacob Jameson </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 1, 2023</p>
    </div>
  </div>
    
  </div>
  

</header><p>Odds ratios have been a long-standing mainstay in health research. Their use can be found sprinkled throughout countless academic journals and research papers. But just because something is popular doesn’t mean it’s the best choice for all contexts. The purpose of this article is to shed light on the limitations of odds ratios, particularly when it comes to interpretation, and advocate for the more intuitive marginal effects and predicted probabilities.</p>
<section id="the-math-behind-odds-ratios" class="level2"><h2 class="anchored" data-anchor-id="the-math-behind-odds-ratios">The math behind odds ratios</h2>
<p>To understand why odds ratios can be confusing, let’s briefly discuss what they represent.</p>
<p>In a logistic regression, the fundamental equation is:</p>
<p><span class="math display">\[log(\frac{p}{1-p}) = \beta_0 + \beta_1X_1 + \beta_2X_2 + ...\]</span></p>
<p>Where <span class="math inline">\(p\)</span> is the probability of an event occurring.</p>
<p>The odds ratio for a given predictor (let’s say <span class="math inline">\(X_1\)</span>) is simply the exponentiated coefficient for that predictor:</p>
<p>Odds Ratio for <span class="math inline">\(X_1 = E^{\beta_1}\)</span></p>
<p>It represents the multiplicative change in the odds of the outcome for a one-unit increase in <span class="math inline">\(X_1\)</span> , holding other variables constant. If this sounds confusing, you’re not alone.</p>
</section><section id="when-odds-ratios-mislead" class="level2"><h2 class="anchored" data-anchor-id="when-odds-ratios-mislead">When Odds Ratios Mislead</h2>
<p>The challenge with odds ratios arises particularly when the outcome of interest is common. The reason being, odds ratios tend to exaggerate relative risks for common outcomes.</p>
<p>Let’s say we find an odds ratio of 2 for a drug reducing heart attack risk. Many might (mistakenly) interpret this as “patients on the drug are twice as likely to avoid heart attacks.” In reality, they have twice the odds, which doesn’t translate directly to actual probabilities, especially when the event is common.</p>
</section><section id="marginal-effects-clarity-over-confusion" class="level2"><h2 class="anchored" data-anchor-id="marginal-effects-clarity-over-confusion">Marginal Effects: Clarity over Confusion</h2>
<p>Marginal effects shine where odds ratios falter. They convey the change in the probability of an outcome for a one-unit change in the predictor, holding other variables constant. It’s a direct measure that offers a tangible understanding of impact.</p>
<p>Mathematically, for a binary predictor (like drug use: yes or no):</p>
<p><span class="math display">\[\text{Marginal Effect} (dy/dx) = P(Y = 1|X=1) - P(Y=1|X=0)\]</span></p>
<p>For continuous predictors, the marginal effect represents the derivative of the probability with respect to the predictor, which essentially gives us the rate of change.</p>
</section><section id="predicted-probabilities-concrete-scenarios-over-abstract-odds" class="level2"><h2 class="anchored" data-anchor-id="predicted-probabilities-concrete-scenarios-over-abstract-odds">Predicted Probabilities: Concrete Scenarios Over Abstract Odds</h2>
<p>Predicted probabilities go a step further, providing the likelihood of an outcome under specific conditions. Instead of leaving things in the realm of odds and abstract increases, we can state tangible scenarios.</p>
</section><section id="demonstrating-with-real-world-data" class="level2"><h2 class="anchored" data-anchor-id="demonstrating-with-real-world-data">Demonstrating with “Real-World” Data</h2>
<p>To provide concrete evidence of the limitations of odds ratios, let’s explore a simulated dataset that mirrors a health study on heart attacks, age, and drug use for high-risk individuals.</p>
<p>First, we’ll generate a dataset with age as a continuous predictor and drug_use as a binary predictor:</p>
<p><em>Simulate data</em></p>
<div class="cell">
<details><summary>Show the code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Setting the seed for reproducibility</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span></span>
<span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fl">1000</span></span>
<span></span>
<span><span class="co"># Age distribution: Normally distributed between 40 and 70</span></span>
<span><span class="va">age</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">55</span>, <span class="fl">7.5</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Drug use: 50% of the participants use the drug</span></span>
<span><span class="va">drug_use</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">1</span>, <span class="fl">0.5</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Log odds of heart attack: Base risk, then increasing slightly with age, </span></span>
<span><span class="co"># and decreasing with drug use (this is where we're setting the odds ratio to roughly 2 for drug use)</span></span>
<span><span class="va">log_odds_heart_attack</span> <span class="op">&lt;-</span> <span class="op">-</span><span class="fl">2</span> <span class="op">+</span> <span class="fl">0.04</span> <span class="op">*</span> <span class="va">age</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="fl">2</span><span class="op">)</span> <span class="op">*</span> <span class="va">drug_use</span></span>
<span></span>
<span><span class="co"># Converting log odds to probability</span></span>
<span><span class="va">prob_heart_attack</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">log_odds_heart_attack</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">log_odds_heart_attack</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Simulating whether a heart attack occurs or not</span></span>
<span><span class="va">heart_attack</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">n</span>, <span class="fl">1</span>, <span class="va">prob_heart_attack</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Create a dataframe</span></span>
<span><span class="va">data_high_risk</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">age</span>, <span class="va">drug_use</span>, <span class="va">heart_attack</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_high_risk</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">data_high_risk</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">

<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 15px; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:right;"> age </th>
   <th style="text-align:right;"> drug_use </th>
   <th style="text-align:right;"> heart_attack </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:right;"> 45.94701 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
<tr>
<td style="text-align:right;"> 57.08072 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
<tr>
<td style="text-align:right;"> 63.13331 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
<tr>
<td style="text-align:right;"> 37.40727 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
<tr>
<td style="text-align:right;"> 58.21844 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
<tr>
<td style="text-align:right;"> 58.79542 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
<tr>
<td style="text-align:right;"> 50.68945 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
<tr>
<td style="text-align:right;"> 50.90026 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
<tr>
<td style="text-align:right;"> 50.76661 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
<tr>
<td style="text-align:right;"> 48.32472 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
</tbody>
</table>
</div>
</div>
<section id="modeling-and-results" class="level3"><h3 class="anchored" data-anchor-id="modeling-and-results">Modeling and Results</h3>
<p>Using a logistic regression, we’ll model the probability of a heart attack based on age and drug use:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">model_high_risk</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">heart_attack</span> <span class="op">~</span> <span class="va">age</span> <span class="op">+</span> <span class="va">drug_use</span>, </span>
<span>                       data<span class="op">=</span><span class="va">data_high_risk</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">model_high_risk</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = heart_attack ~ age + drug_use, family = binomial, 
    data = data_high_risk)

Deviance Residuals: 
   Min      1Q  Median      3Q     Max  
-1.662  -1.049  -0.854   1.188   1.685  

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.24031    0.49848  -4.494 6.98e-06 ***
age          0.04281    0.00896   4.777 1.78e-06 ***
drug_use    -0.66254    0.13064  -5.072 3.94e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1373.7  on 999  degrees of freedom
Residual deviance: 1324.4  on 997  degrees of freedom
AIC: 1330.4

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Upon examining the output, you’ll observe an odds ratio close to 2 for drug use (exponentiate the coeffecient). A common misinterpretation might be: “Patients on the drug have twice the likelihood to avoid heart attacks.” This is a misconception. They have twice the odds, not twice the probability. This distinction becomes especially murky when the event (heart attack) is common.</p>
</section><section id="marginal-effects-and-interpretation" class="level3"><h3 class="anchored" data-anchor-id="marginal-effects-and-interpretation">Marginal Effects and Interpretation</h3>
<p>The marginal effect of the drug can be found by computing the difference in predicted probabilities between drug users and non-users, holding other variables constant. This gives a more direct measure of the drug’s impact on the probability of heart attack.</p>
<p>Using our model, you can compute the marginal effect for any given age. For example, for someone aged 55:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">predicted_prob_on_drug</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model_high_risk</span>, </span>
<span>                                  newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>age <span class="op">=</span> <span class="fl">55</span>, drug_use <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                                  type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">predicted_prob_off_drug</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model_high_risk</span>, </span>
<span>                                   newdata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>age <span class="op">=</span> <span class="fl">55</span>, drug_use <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>,</span>
<span>                                   type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">marginal_effect_55</span> <span class="op">&lt;-</span> <span class="va">predicted_prob_on_drug</span> <span class="op">-</span> <span class="va">predicted_prob_off_drug</span></span>
<span></span>
<span><span class="va">marginal_effect_55</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1 
-0.1622666 </code></pre>
</div>
</div>
<p>The result is a clear percentage point decrease in the probability of a heart attack for drug users compared to non-users.</p>
<p><strong>This means that, for individuals aged 55, using the drug results in a 16 percentage point decrease in the probability of experiencing a heart attack compared to those not using the drug.</strong> This direct interpretation offers a tangible sense of the drug’s impact and is far more intuitive than grappling with odds ratios.</p>
</section></section><section id="average-marginal-effects-a-comprehensive-view" class="level2"><h2 class="anchored" data-anchor-id="average-marginal-effects-a-comprehensive-view">Average Marginal Effects: A Comprehensive View</h2>
<p>Beyond just evaluating the marginal effect at specific values, we can compute the average marginal effect (AME) across our sample. AMEs provide a holistic view of the predictor’s impact by averaging its effects over all observations in our dataset. It’s particularly insightful when dealing with continuous predictors like age.</p>
<section id="computing-the-average-marginal-effects" class="level3"><h3 class="anchored" data-anchor-id="computing-the-average-marginal-effects">Computing the Average Marginal Effects</h3>
<p>To compute the AMEs in R, <a href="https://cran.r-project.org/web/packages/margins/vignettes/Introduction.html">you can leverage the <code>margins</code> package</a>:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#install.packages("margins")</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/leeper/margins">margins</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">ame</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/margins/man/margins.html">margins</a></span><span class="op">(</span><span class="va">model_high_risk</span>, variables <span class="op">=</span> <span class="st">"drug_use"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">ame</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   factor     AME     SE       z      p   lower   upper
 drug_use -0.1556 0.0291 -5.3429 0.0000 -0.2127 -0.0985</code></pre>
</div>
</div>
<p>This will give you the average marginal effect of drug use on the probability of a heart attack across all ages in the dataset.</p>
</section><section id="interpreting-the-ames" class="level3"><h3 class="anchored" data-anchor-id="interpreting-the-ames">Interpreting the AMEs</h3>
<p>Suppose the AME for drug use is -0.156. This means that, on average, across all ages in our sample, using the drug is associated with a 15.6 percentage point decrease in the probability of experiencing a heart attack relative to not using the drug.</p>
<p>This single number provides an overarching sense of the drug’s impact, making it immensely useful for policy and clinical decisions. For instance, in public health discussions or in communications with patients, being able to state the average effect of a treatment can be more practical than specifying its impact at particular ages or conditions.</p>
<p>By incorporating AMEs into your analysis, you’re providing an extra layer of depth to your findings. This approach shifts the discussion from “what might the effect be?” to “here’s the effect, on average, across our population.” When combined with specific marginal effects and predicted probabilities, this trio offers a robust, comprehensive, and intuitive understanding of your predictors’ impacts.</p>
</section></section><section id="visualizing-predicted-probabilities" class="level2"><h2 class="anchored" data-anchor-id="visualizing-predicted-probabilities">Visualizing Predicted Probabilities</h2>
<p>To provide a tangible representation, let’s plot the predicted probabilities of heart attacks by age from our model:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">data_high_risk</span><span class="op">$</span><span class="va">predicted_prob</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model_high_risk</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span></span>
<span><span class="va">predictions</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">model_high_risk</span>, type <span class="op">=</span> <span class="st">"response"</span>, se.fit <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">data_high_risk</span><span class="op">$</span><span class="va">lower_ci</span> <span class="op">&lt;-</span> <span class="va">predictions</span><span class="op">$</span><span class="va">fit</span> <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">predictions</span><span class="op">$</span><span class="va">se.fit</span></span>
<span><span class="va">data_high_risk</span><span class="op">$</span><span class="va">upper_ci</span> <span class="op">&lt;-</span> <span class="va">predictions</span><span class="op">$</span><span class="va">fit</span> <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> <span class="va">predictions</span><span class="op">$</span><span class="va">se.fit</span></span>
<span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">data_high_risk</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, </span>
<span>                           y <span class="op">=</span> <span class="va">predicted_prob</span>, </span>
<span>                           color <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">drug_use</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">lower_ci</span>, </span>
<span>                  ymax <span class="op">=</span> <span class="va">upper_ci</span>, </span>
<span>                  fill <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">drug_use</span><span class="op">)</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Predicted Probability of Heart Attack by Age with 95% CI"</span>,</span>
<span>       y <span class="op">=</span> <span class="st">"Predicted Probability"</span>,</span>
<span>       x <span class="op">=</span> <span class="st">"Age"</span>,</span>
<span>       color <span class="op">=</span> <span class="st">"Drug Use"</span>,</span>
<span>       fill <span class="op">=</span> <span class="st">"Drug Use"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_color_discrete</a></span><span class="op">(</span>labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"No Drug"</span>, <span class="st">"On Drug"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_colour_discrete.html">scale_fill_discrete</a></span><span class="op">(</span>labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"No Drug"</span>, <span class="st">"On Drug"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="2023-09-01-OR_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The visual clearly illustrates the beneficial effect of the drug over time. It gives a tangible sense of how the risk of heart attacks evolves with age for both groups and the significant advantage of drug users. This can be especially useful for diagnostic purposes or to demonstrate the results of your model to stakeholders.</p>
</section><section id="conclusion-a-call-to-transition" class="level2"><h2 class="anchored" data-anchor-id="conclusion-a-call-to-transition">Conclusion: A Call to Transition</h2>
<p>The era of odds ratios has provided us with valuable insights, but as the field of health research progresses, so should our statistical tools and reporting practices. Marginal effects and predicted probabilities provide clearer, more intuitive insights, pushing us away from the ambiguous realm of odds and into the tangible world of real impact.</p>
<p>After all, the end goal of our research is to provide clear, actionable insights that can be readily applied to improve health outcomes. Let’s choose clarity over tradition, and marginal effects over odds ratios.</p>
<p>Thank you!</p>
<p>Jacob</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><script src="https://utteranc.es/client.js" repo="jacobjameson/jacobjameson.github.io" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Jacob Jameson</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jacobjameson/jacobjameson.github.io">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/JacobCJameson">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
</ul>
</div>
  </div>
</footer>


</body></html>