---
title: "Introduction to Programming in R"
from: markdown+emoji
page-layout: full
---

## About this course

This page contains the content for the "Introduction to Data Analysis in R" mini-course. The goal is to introduce R programming concepts with a focus on preparing and analyzing data, and conducting statistical simulations. We will cover how to read data into R, manipulate data with a suite of tools from the tidyverse package dplyr. We will also discuss some basic programming concepts including data types and operators.


This mini-course is aimed at people with no programming background that are looking for a gentle and practical introduction to data analysis in R.


Each Module involves:

- a pre-recorded lecture with guided practice exercises
- a corresponding lab to practice the skills taught in the video and stretch your thinking


The labs are an essential part of the learning process as they walkthrough the use of many key functions and topics that are not explicitly covered in the videos.


## Table of Contents

- Module 0: R and RStudio Installation Guide

- Module 1: An Introduction and Motivation for R Programming

- Module 2: Installing Packages and Reading Data

- Module 3: Vectors and Lists

- Module 4: Data Manipulation

- Module 5: Data Manipulation and Analysis II

- Module 6: Data Visualization as a Tool for Analysis

- Module 7: Grouped Analysis

- Module 8: Iteration

- Module 9: Writing Functions


<p style="font-weight: bold; color:#8B0000;">Additional Resources</p>

<ul>
  <li><a href="https://rstudio.com/resources/cheatsheets/">tidyverse cheetsheets</a> start with dplyr and ggplot</li>
  <li><a href="https://r4ds.had.co.nz">R for Data Science</a>: free online book with clear explanations of many tidyverse functions, the book to read on data analysis with R</li>
</ul>
